/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
export interface ActionResult {
    success: boolean;
    message: string;
}
//# sourceMappingURL=actionResult.d.ts.map