/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface Patient {
    id: number;
    name: string;
    mrn: string;
    /** @nullable */
    dateOfBirth?: string | null;
    /** @nullable */
    department?: string | null;
    createdAt?: string;
}
export interface PatientInput {
    /** @minLength 1 */
    name: string;
    /** @minLength 1 */
    mrn: string;
    /** @nullable */
    dateOfBirth?: string | null;
    /** @nullable */
    department?: string | null;
}
export interface Doctor {
    id: number;
    name: string;
    /** @nullable */
    specialty?: string | null;
    /** @nullable */
    email?: string | null;
    createdAt?: string;
}
export interface DoctorInput {
    /** @minLength 1 */
    name: string;
    /** @nullable */
    specialty?: string | null;
    /** @nullable */
    email?: string | null;
}
export type KnowledgeNodeType = typeof KnowledgeNodeType[keyof typeof KnowledgeNodeType];
export declare const KnowledgeNodeType: {
    readonly CONSTRAINT: "CONSTRAINT";
    readonly DECISION: "DECISION";
    readonly ANTI_PATTERN: "ANTI_PATTERN";
    readonly FACT: "FACT";
};
export type KnowledgeNodeStatus = typeof KnowledgeNodeStatus[keyof typeof KnowledgeNodeStatus];
export declare const KnowledgeNodeStatus: {
    readonly PENDING_CONFIRMATION: "PENDING_CONFIRMATION";
    readonly ACTIVE: "ACTIVE";
    readonly DISMISSED: "DISMISSED";
    readonly MERGED: "MERGED";
};
export type KnowledgeNodeLevel = typeof KnowledgeNodeLevel[keyof typeof KnowledgeNodeLevel];
export declare const KnowledgeNodeLevel: {
    readonly patient: "patient";
    readonly department: "department";
    readonly organization: "organization";
};
export interface KnowledgeNode {
    id: number;
    type: KnowledgeNodeType;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    status: KnowledgeNodeStatus;
    level: KnowledgeNodeLevel;
    /** @nullable */
    department: string | null;
    /** @nullable */
    rationale?: string | null;
    /** @nullable */
    patientId?: number | null;
    /** @nullable */
    doctorId?: number | null;
    createdAt?: string;
    updatedAt?: string;
}
export interface PatientContext {
    patient: Patient;
    knowledgeNodes: KnowledgeNode[];
}
/**
 * @nullable
 */
export type KnowledgeNodeUpdateType = typeof KnowledgeNodeUpdateType[keyof typeof KnowledgeNodeUpdateType] | null;
export declare const KnowledgeNodeUpdateType: {
    readonly CONSTRAINT: "CONSTRAINT";
    readonly DECISION: "DECISION";
    readonly ANTI_PATTERN: "ANTI_PATTERN";
    readonly FACT: "FACT";
};
/**
 * @nullable
 */
export type KnowledgeNodeUpdateStatus = typeof KnowledgeNodeUpdateStatus[keyof typeof KnowledgeNodeUpdateStatus] | null;
export declare const KnowledgeNodeUpdateStatus: {
    readonly ACTIVE: "ACTIVE";
    readonly PENDING_CONFIRMATION: "PENDING_CONFIRMATION";
    readonly DISMISSED: "DISMISSED";
};
export interface KnowledgeNodeUpdate {
    /** @nullable */
    type?: KnowledgeNodeUpdateType;
    /** @nullable */
    title?: string | null;
    /** @nullable */
    content?: string | null;
    /** @nullable */
    importance?: number | null;
    /** @nullable */
    rationale?: string | null;
    /** @nullable */
    status?: KnowledgeNodeUpdateStatus;
}
export type CaptureCandidateType = typeof CaptureCandidateType[keyof typeof CaptureCandidateType];
export declare const CaptureCandidateType: {
    readonly CONSTRAINT: "CONSTRAINT";
    readonly DECISION: "DECISION";
    readonly ANTI_PATTERN: "ANTI_PATTERN";
    readonly FACT: "FACT";
};
export type CaptureCandidateConfidenceTier = typeof CaptureCandidateConfidenceTier[keyof typeof CaptureCandidateConfidenceTier];
export declare const CaptureCandidateConfidenceTier: {
    readonly HIGH: "HIGH";
    readonly MEDIUM: "MEDIUM";
    readonly LOW: "LOW";
};
export type CaptureCandidateSuggestedLevel = typeof CaptureCandidateSuggestedLevel[keyof typeof CaptureCandidateSuggestedLevel];
export declare const CaptureCandidateSuggestedLevel: {
    readonly patient: "patient";
    readonly department: "department";
    readonly organization: "organization";
};
export type CaptureCandidateStatus = typeof CaptureCandidateStatus[keyof typeof CaptureCandidateStatus];
export declare const CaptureCandidateStatus: {
    readonly PENDING: "PENDING";
    readonly CONFIRMED: "CONFIRMED";
    readonly DISMISSED: "DISMISSED";
    readonly MERGED: "MERGED";
};
export interface CaptureCandidate {
    id: number;
    type: CaptureCandidateType;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    confidenceTier: CaptureCandidateConfidenceTier;
    suggestedLevel: CaptureCandidateSuggestedLevel;
    department: string;
    rationale: string;
    patientId: number;
    doctorId: number;
    status?: CaptureCandidateStatus;
    createdAt?: string;
}
export interface ExtractInput {
    transcript: string;
    patientId: number;
    doctorId: number;
}
export interface ConflictDetectInput {
    candidateId: number;
}
export type ConflictResultConflictType = typeof ConflictResultConflictType[keyof typeof ConflictResultConflictType];
export declare const ConflictResultConflictType: {
    readonly NEW: "NEW";
    readonly COEXIST: "COEXIST";
    readonly UPDATE: "UPDATE";
    readonly DUPLICATE: "DUPLICATE";
};
/**
 * @nullable
 */
export type ConflictResultExistingNode = {
    [key: string]: unknown;
} | null;
export interface ConflictResult {
    candidateId: number;
    conflictType: ConflictResultConflictType;
    similarity: number;
    /** @nullable */
    existingNode?: ConflictResultExistingNode;
}
/**
 * @nullable
 */
export type ConfirmNodeInputEditedType = typeof ConfirmNodeInputEditedType[keyof typeof ConfirmNodeInputEditedType] | null;
export declare const ConfirmNodeInputEditedType: {
    readonly CONSTRAINT: "CONSTRAINT";
    readonly DECISION: "DECISION";
    readonly ANTI_PATTERN: "ANTI_PATTERN";
    readonly FACT: "FACT";
};
export interface ConfirmNodeInput {
    candidateId: number;
    /** @nullable */
    editedType?: ConfirmNodeInputEditedType;
    /** @nullable */
    editedTitle?: string | null;
    /** @nullable */
    editedContent?: string | null;
    /** @nullable */
    editedRationale?: string | null;
}
export interface DismissNodeInput {
    candidateId: number;
}
export interface MergeNodeInput {
    candidateId: number;
    existingNodeId: number;
    /** @nullable */
    mergedContent?: string | null;
}
export interface UndoNodeInput {
    nodeId: number;
}
export interface CountByLabel {
    label: string;
    count: number;
}
/**
 * @nullable
 */
export type EventLogMetadata = {
    [key: string]: unknown;
} | null;
export interface EventLog {
    id: number;
    eventType: string;
    /** @nullable */
    candidateId?: number | null;
    /** @nullable */
    nodeId?: number | null;
    /** @nullable */
    doctorId?: number | null;
    /** @nullable */
    patientId?: number | null;
    /** @nullable */
    metadata?: EventLogMetadata;
    createdAt: string;
}
export interface CaptureSummary {
    totalNodes: number;
    activeNodes: number;
    pendingNodes: number;
    todayCaptures: number;
    byType: CountByLabel[];
    byDepartment: CountByLabel[];
    byConfidenceTier: CountByLabel[];
    recentActivity: EventLog[];
}
export interface SemanticSearchBody {
    query: string;
    topK?: number;
}
export interface SemanticSearchResult {
    node: KnowledgeNode;
    similarity: number;
}
export interface OpenAIHealth {
    configured: boolean;
    status: string;
}
export interface DoctorContext {
    doctor: Doctor;
    knowledgeNodes: KnowledgeNode[];
}
export interface ActionResult {
    success: boolean;
    message: string;
}
export interface TranscriptionResult {
    transcript: string;
}
export type ListKnowledgeNodesParams = {
    /**
     * @nullable
     */
    patientId?: number | null;
    /**
     * @nullable
     */
    doctorId?: number | null;
    /**
     * @nullable
     */
    department?: string | null;
    /**
     * @nullable
     */
    type?: string | null;
    /**
     * @nullable
     */
    status?: string | null;
};
export type ListEventsParams = {
    /**
     * @nullable
     */
    limit?: number | null;
};
//# sourceMappingURL=api.schemas.d.ts.map