/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Check if OpenAI API key is configured and usable
 */
export declare const CheckOpenAIHealthResponse: zod.ZodObject<{
    configured: zod.ZodBoolean;
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    configured: boolean;
}, {
    status: string;
    configured: boolean;
}>;
/**
 * @summary List all patients
 */
export declare const ListPatientsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    mrn: zod.ZodString;
    dateOfBirth: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    mrn: string;
    dateOfBirth?: string | null | undefined;
    department?: string | null | undefined;
    createdAt?: string | undefined;
}, {
    id: number;
    name: string;
    mrn: string;
    dateOfBirth?: string | null | undefined;
    department?: string | null | undefined;
    createdAt?: string | undefined;
}>;
export declare const ListPatientsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    mrn: zod.ZodString;
    dateOfBirth: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    mrn: string;
    dateOfBirth?: string | null | undefined;
    department?: string | null | undefined;
    createdAt?: string | undefined;
}, {
    id: number;
    name: string;
    mrn: string;
    dateOfBirth?: string | null | undefined;
    department?: string | null | undefined;
    createdAt?: string | undefined;
}>, "many">;
/**
 * @summary Create a new patient
 */
export declare const CreatePatientBody: zod.ZodObject<{
    name: zod.ZodString;
    mrn: zod.ZodString;
    dateOfBirth: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    mrn: string;
    dateOfBirth?: string | null | undefined;
    department?: string | null | undefined;
}, {
    name: string;
    mrn: string;
    dateOfBirth?: string | null | undefined;
    department?: string | null | undefined;
}>;
/**
 * @summary Get patient context nodes
 */
export declare const GetPatientContextParams: zod.ZodObject<{
    patientId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    patientId: number;
}, {
    patientId: number;
}>;
export declare const GetPatientContextResponse: zod.ZodObject<{
    patient: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        mrn: zod.ZodString;
        dateOfBirth: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        createdAt: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        mrn: string;
        dateOfBirth?: string | null | undefined;
        department?: string | null | undefined;
        createdAt?: string | undefined;
    }, {
        id: number;
        name: string;
        mrn: string;
        dateOfBirth?: string | null | undefined;
        department?: string | null | undefined;
        createdAt?: string | undefined;
    }>;
    knowledgeNodes: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
        title: zod.ZodString;
        content: zod.ZodString;
        importance: zod.ZodNumber;
        confidence: zod.ZodNumber;
        status: zod.ZodEnum<["PENDING_CONFIRMATION", "ACTIVE", "DISMISSED", "MERGED"]>;
        level: zod.ZodEnum<["patient", "department", "organization"]>;
        department: zod.ZodNullable<zod.ZodString>;
        rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        createdAt: zod.ZodOptional<zod.ZodString>;
        updatedAt: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }, {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    patient: {
        id: number;
        name: string;
        mrn: string;
        dateOfBirth?: string | null | undefined;
        department?: string | null | undefined;
        createdAt?: string | undefined;
    };
    knowledgeNodes: {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }[];
}, {
    patient: {
        id: number;
        name: string;
        mrn: string;
        dateOfBirth?: string | null | undefined;
        department?: string | null | undefined;
        createdAt?: string | undefined;
    };
    knowledgeNodes: {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }[];
}>;
/**
 * @summary List all doctors
 */
export declare const ListDoctorsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    specialty: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    createdAt?: string | undefined;
    specialty?: string | null | undefined;
    email?: string | null | undefined;
}, {
    id: number;
    name: string;
    createdAt?: string | undefined;
    specialty?: string | null | undefined;
    email?: string | null | undefined;
}>;
export declare const ListDoctorsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    specialty: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    createdAt?: string | undefined;
    specialty?: string | null | undefined;
    email?: string | null | undefined;
}, {
    id: number;
    name: string;
    createdAt?: string | undefined;
    specialty?: string | null | undefined;
    email?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a new doctor
 */
export declare const CreateDoctorBody: zod.ZodObject<{
    name: zod.ZodString;
    specialty: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    specialty?: string | null | undefined;
    email?: string | null | undefined;
}, {
    name: string;
    specialty?: string | null | undefined;
    email?: string | null | undefined;
}>;
/**
 * @summary Get doctor context — their nodes and stats
 */
export declare const GetDoctorContextParams: zod.ZodObject<{
    doctorId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    doctorId: number;
}, {
    doctorId: number;
}>;
export declare const GetDoctorContextResponse: zod.ZodObject<{
    doctor: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        specialty: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        createdAt: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        name: string;
        createdAt?: string | undefined;
        specialty?: string | null | undefined;
        email?: string | null | undefined;
    }, {
        id: number;
        name: string;
        createdAt?: string | undefined;
        specialty?: string | null | undefined;
        email?: string | null | undefined;
    }>;
    knowledgeNodes: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
        title: zod.ZodString;
        content: zod.ZodString;
        importance: zod.ZodNumber;
        confidence: zod.ZodNumber;
        status: zod.ZodEnum<["PENDING_CONFIRMATION", "ACTIVE", "DISMISSED", "MERGED"]>;
        level: zod.ZodEnum<["patient", "department", "organization"]>;
        department: zod.ZodNullable<zod.ZodString>;
        rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        createdAt: zod.ZodOptional<zod.ZodString>;
        updatedAt: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }, {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    knowledgeNodes: {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }[];
    doctor: {
        id: number;
        name: string;
        createdAt?: string | undefined;
        specialty?: string | null | undefined;
        email?: string | null | undefined;
    };
}, {
    knowledgeNodes: {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }[];
    doctor: {
        id: number;
        name: string;
        createdAt?: string | undefined;
        specialty?: string | null | undefined;
        email?: string | null | undefined;
    };
}>;
/**
 * @summary Extract knowledge nodes from transcript using LLM
 */
export declare const ExtractKnowledgeBody: zod.ZodObject<{
    transcript: zod.ZodString;
    patientId: zod.ZodNumber;
    doctorId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    patientId: number;
    doctorId: number;
    transcript: string;
}, {
    patientId: number;
    doctorId: number;
    transcript: string;
}>;
export declare const ExtractKnowledgeResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
    title: zod.ZodString;
    content: zod.ZodString;
    importance: zod.ZodNumber;
    confidence: zod.ZodNumber;
    confidenceTier: zod.ZodEnum<["HIGH", "MEDIUM", "LOW"]>;
    suggestedLevel: zod.ZodEnum<["patient", "department", "organization"]>;
    department: zod.ZodString;
    rationale: zod.ZodString;
    patientId: zod.ZodNumber;
    doctorId: zod.ZodNumber;
    status: zod.ZodOptional<zod.ZodEnum<["PENDING", "CONFIRMED", "DISMISSED", "MERGED"]>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string;
    patientId: number;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    rationale: string;
    doctorId: number;
    confidenceTier: "HIGH" | "MEDIUM" | "LOW";
    suggestedLevel: "department" | "patient" | "organization";
    status?: "DISMISSED" | "MERGED" | "PENDING" | "CONFIRMED" | undefined;
    createdAt?: string | undefined;
}, {
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string;
    patientId: number;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    rationale: string;
    doctorId: number;
    confidenceTier: "HIGH" | "MEDIUM" | "LOW";
    suggestedLevel: "department" | "patient" | "organization";
    status?: "DISMISSED" | "MERGED" | "PENDING" | "CONFIRMED" | undefined;
    createdAt?: string | undefined;
}>;
export declare const ExtractKnowledgeResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
    title: zod.ZodString;
    content: zod.ZodString;
    importance: zod.ZodNumber;
    confidence: zod.ZodNumber;
    confidenceTier: zod.ZodEnum<["HIGH", "MEDIUM", "LOW"]>;
    suggestedLevel: zod.ZodEnum<["patient", "department", "organization"]>;
    department: zod.ZodString;
    rationale: zod.ZodString;
    patientId: zod.ZodNumber;
    doctorId: zod.ZodNumber;
    status: zod.ZodOptional<zod.ZodEnum<["PENDING", "CONFIRMED", "DISMISSED", "MERGED"]>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string;
    patientId: number;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    rationale: string;
    doctorId: number;
    confidenceTier: "HIGH" | "MEDIUM" | "LOW";
    suggestedLevel: "department" | "patient" | "organization";
    status?: "DISMISSED" | "MERGED" | "PENDING" | "CONFIRMED" | undefined;
    createdAt?: string | undefined;
}, {
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string;
    patientId: number;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    rationale: string;
    doctorId: number;
    confidenceTier: "HIGH" | "MEDIUM" | "LOW";
    suggestedLevel: "department" | "patient" | "organization";
    status?: "DISMISSED" | "MERGED" | "PENDING" | "CONFIRMED" | undefined;
    createdAt?: string | undefined;
}>, "many">;
/**
 * @summary Generate embedding and detect conflicts via cosine similarity search
 */
export declare const DetectConflictsBody: zod.ZodObject<{
    candidateId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    candidateId: number;
}, {
    candidateId: number;
}>;
export declare const DetectConflictsResponse: zod.ZodObject<{
    candidateId: zod.ZodNumber;
    conflictType: zod.ZodEnum<["NEW", "COEXIST", "UPDATE", "DUPLICATE"]>;
    similarity: zod.ZodNumber;
    existingNode: zod.ZodOptional<zod.ZodNullable<zod.ZodObject<{}, "passthrough", zod.ZodTypeAny, zod.objectOutputType<{}, zod.ZodTypeAny, "passthrough">, zod.objectInputType<{}, zod.ZodTypeAny, "passthrough">>>>;
}, "strip", zod.ZodTypeAny, {
    candidateId: number;
    conflictType: "NEW" | "COEXIST" | "UPDATE" | "DUPLICATE";
    similarity: number;
    existingNode?: zod.objectOutputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
}, {
    candidateId: number;
    conflictType: "NEW" | "COEXIST" | "UPDATE" | "DUPLICATE";
    similarity: number;
    existingNode?: zod.objectInputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
}>;
/**
 * @summary Confirm and create a knowledge node
 */
export declare const ConfirmNodeBody: zod.ZodObject<{
    candidateId: zod.ZodNumber;
    editedType: zod.ZodOptional<zod.ZodNullable<zod.ZodUnion<[zod.ZodLiteral<"CONSTRAINT">, zod.ZodLiteral<"DECISION">, zod.ZodLiteral<"ANTI_PATTERN">, zod.ZodLiteral<"FACT">, zod.ZodLiteral<null>]>>>;
    editedTitle: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    editedContent: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    editedRationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    candidateId: number;
    editedType?: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT" | null | undefined;
    editedTitle?: string | null | undefined;
    editedContent?: string | null | undefined;
    editedRationale?: string | null | undefined;
}, {
    candidateId: number;
    editedType?: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT" | null | undefined;
    editedTitle?: string | null | undefined;
    editedContent?: string | null | undefined;
    editedRationale?: string | null | undefined;
}>;
/**
 * @summary Dismiss a capture candidate
 */
export declare const DismissNodeBody: zod.ZodObject<{
    candidateId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    candidateId: number;
}, {
    candidateId: number;
}>;
export declare const DismissNodeResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    message: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    success: boolean;
}, {
    message: string;
    success: boolean;
}>;
/**
 * @summary Merge candidate with existing knowledge node
 */
export declare const MergeNodeBody: zod.ZodObject<{
    candidateId: zod.ZodNumber;
    existingNodeId: zod.ZodNumber;
    mergedContent: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    candidateId: number;
    existingNodeId: number;
    mergedContent?: string | null | undefined;
}, {
    candidateId: number;
    existingNodeId: number;
    mergedContent?: string | null | undefined;
}>;
export declare const MergeNodeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
    title: zod.ZodString;
    content: zod.ZodString;
    importance: zod.ZodNumber;
    confidence: zod.ZodNumber;
    status: zod.ZodEnum<["PENDING_CONFIRMATION", "ACTIVE", "DISMISSED", "MERGED"]>;
    level: zod.ZodEnum<["patient", "department", "organization"]>;
    department: zod.ZodNullable<zod.ZodString>;
    rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}>;
/**
 * @summary Undo an auto-captured node within the 60-second window
 */
export declare const UndoNodeBody: zod.ZodObject<{
    nodeId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    nodeId: number;
}, {
    nodeId: number;
}>;
export declare const UndoNodeResponse: zod.ZodObject<{
    success: zod.ZodBoolean;
    message: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    success: boolean;
}, {
    message: string;
    success: boolean;
}>;
/**
 * @summary List knowledge nodes with optional filters
 */
export declare const ListKnowledgeNodesQueryParams: zod.ZodObject<{
    patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    department: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    type: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    status?: string | null | undefined;
    type?: string | null | undefined;
    department?: string | null | undefined;
    patientId?: number | null | undefined;
    doctorId?: number | null | undefined;
}, {
    status?: string | null | undefined;
    type?: string | null | undefined;
    department?: string | null | undefined;
    patientId?: number | null | undefined;
    doctorId?: number | null | undefined;
}>;
export declare const ListKnowledgeNodesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
    title: zod.ZodString;
    content: zod.ZodString;
    importance: zod.ZodNumber;
    confidence: zod.ZodNumber;
    status: zod.ZodEnum<["PENDING_CONFIRMATION", "ACTIVE", "DISMISSED", "MERGED"]>;
    level: zod.ZodEnum<["patient", "department", "organization"]>;
    department: zod.ZodNullable<zod.ZodString>;
    rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}>;
export declare const ListKnowledgeNodesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
    title: zod.ZodString;
    content: zod.ZodString;
    importance: zod.ZodNumber;
    confidence: zod.ZodNumber;
    status: zod.ZodEnum<["PENDING_CONFIRMATION", "ACTIVE", "DISMISSED", "MERGED"]>;
    level: zod.ZodEnum<["patient", "department", "organization"]>;
    department: zod.ZodNullable<zod.ZodString>;
    rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}>, "many">;
/**
 * @summary Semantic similarity search over knowledge nodes
 */
export declare const semanticSearchNodesBodyTopKDefault = 10;
export declare const SemanticSearchNodesBody: zod.ZodObject<{
    query: zod.ZodString;
    topK: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    query: string;
    topK: number;
}, {
    query: string;
    topK?: number | undefined;
}>;
export declare const SemanticSearchNodesResponseItem: zod.ZodObject<{
    node: zod.ZodObject<{
        id: zod.ZodNumber;
        type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
        title: zod.ZodString;
        content: zod.ZodString;
        importance: zod.ZodNumber;
        confidence: zod.ZodNumber;
        status: zod.ZodEnum<["PENDING_CONFIRMATION", "ACTIVE", "DISMISSED", "MERGED"]>;
        level: zod.ZodEnum<["patient", "department", "organization"]>;
        department: zod.ZodNullable<zod.ZodString>;
        rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        createdAt: zod.ZodOptional<zod.ZodString>;
        updatedAt: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }, {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }>;
    similarity: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    similarity: number;
    node: {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    };
}, {
    similarity: number;
    node: {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    };
}>;
export declare const SemanticSearchNodesResponse: zod.ZodArray<zod.ZodObject<{
    node: zod.ZodObject<{
        id: zod.ZodNumber;
        type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
        title: zod.ZodString;
        content: zod.ZodString;
        importance: zod.ZodNumber;
        confidence: zod.ZodNumber;
        status: zod.ZodEnum<["PENDING_CONFIRMATION", "ACTIVE", "DISMISSED", "MERGED"]>;
        level: zod.ZodEnum<["patient", "department", "organization"]>;
        department: zod.ZodNullable<zod.ZodString>;
        rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        createdAt: zod.ZodOptional<zod.ZodString>;
        updatedAt: zod.ZodOptional<zod.ZodString>;
    }, "strip", zod.ZodTypeAny, {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }, {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    }>;
    similarity: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    similarity: number;
    node: {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    };
}, {
    similarity: number;
    node: {
        status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
        type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
        id: number;
        department: string | null;
        title: string;
        content: string;
        importance: number;
        confidence: number;
        level: "department" | "patient" | "organization";
        createdAt?: string | undefined;
        patientId?: number | null | undefined;
        rationale?: string | null | undefined;
        doctorId?: number | null | undefined;
        updatedAt?: string | undefined;
    };
}>, "many">;
/**
 * @summary Get a single knowledge node
 */
export declare const GetKnowledgeNodeParams: zod.ZodObject<{
    nodeId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    nodeId: number;
}, {
    nodeId: number;
}>;
export declare const GetKnowledgeNodeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
    title: zod.ZodString;
    content: zod.ZodString;
    importance: zod.ZodNumber;
    confidence: zod.ZodNumber;
    status: zod.ZodEnum<["PENDING_CONFIRMATION", "ACTIVE", "DISMISSED", "MERGED"]>;
    level: zod.ZodEnum<["patient", "department", "organization"]>;
    department: zod.ZodNullable<zod.ZodString>;
    rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}>;
/**
 * @summary Update a knowledge node
 */
export declare const UpdateKnowledgeNodeParams: zod.ZodObject<{
    nodeId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    nodeId: number;
}, {
    nodeId: number;
}>;
export declare const UpdateKnowledgeNodeBody: zod.ZodObject<{
    type: zod.ZodOptional<zod.ZodNullable<zod.ZodUnion<[zod.ZodLiteral<"CONSTRAINT">, zod.ZodLiteral<"DECISION">, zod.ZodLiteral<"ANTI_PATTERN">, zod.ZodLiteral<"FACT">, zod.ZodLiteral<null>]>>>;
    title: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    content: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    importance: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    status: zod.ZodOptional<zod.ZodNullable<zod.ZodUnion<[zod.ZodLiteral<"ACTIVE">, zod.ZodLiteral<"PENDING_CONFIRMATION">, zod.ZodLiteral<"DISMISSED">, zod.ZodLiteral<null>]>>>;
}, "strip", zod.ZodTypeAny, {
    status?: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | null | undefined;
    type?: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT" | null | undefined;
    title?: string | null | undefined;
    content?: string | null | undefined;
    importance?: number | null | undefined;
    rationale?: string | null | undefined;
}, {
    status?: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | null | undefined;
    type?: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT" | null | undefined;
    title?: string | null | undefined;
    content?: string | null | undefined;
    importance?: number | null | undefined;
    rationale?: string | null | undefined;
}>;
export declare const UpdateKnowledgeNodeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    type: zod.ZodEnum<["CONSTRAINT", "DECISION", "ANTI_PATTERN", "FACT"]>;
    title: zod.ZodString;
    content: zod.ZodString;
    importance: zod.ZodNumber;
    confidence: zod.ZodNumber;
    status: zod.ZodEnum<["PENDING_CONFIRMATION", "ACTIVE", "DISMISSED", "MERGED"]>;
    level: zod.ZodEnum<["patient", "department", "organization"]>;
    department: zod.ZodNullable<zod.ZodString>;
    rationale: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodOptional<zod.ZodString>;
    updatedAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}, {
    status: "PENDING_CONFIRMATION" | "ACTIVE" | "DISMISSED" | "MERGED";
    type: "CONSTRAINT" | "DECISION" | "ANTI_PATTERN" | "FACT";
    id: number;
    department: string | null;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    level: "department" | "patient" | "organization";
    createdAt?: string | undefined;
    patientId?: number | null | undefined;
    rationale?: string | null | undefined;
    doctorId?: number | null | undefined;
    updatedAt?: string | undefined;
}>;
/**
 * @summary Get dashboard summary of capture pipeline stats
 */
export declare const GetCaptureSummaryResponse: zod.ZodObject<{
    totalNodes: zod.ZodNumber;
    activeNodes: zod.ZodNumber;
    pendingNodes: zod.ZodNumber;
    todayCaptures: zod.ZodNumber;
    byType: zod.ZodArray<zod.ZodObject<{
        label: zod.ZodString;
        count: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        label: string;
        count: number;
    }, {
        label: string;
        count: number;
    }>, "many">;
    byDepartment: zod.ZodArray<zod.ZodObject<{
        label: zod.ZodString;
        count: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        label: string;
        count: number;
    }, {
        label: string;
        count: number;
    }>, "many">;
    byConfidenceTier: zod.ZodArray<zod.ZodObject<{
        label: zod.ZodString;
        count: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        label: string;
        count: number;
    }, {
        label: string;
        count: number;
    }>, "many">;
    recentActivity: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        eventType: zod.ZodString;
        candidateId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        nodeId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        metadata: zod.ZodOptional<zod.ZodNullable<zod.ZodObject<{}, "passthrough", zod.ZodTypeAny, zod.objectOutputType<{}, zod.ZodTypeAny, "passthrough">, zod.objectInputType<{}, zod.ZodTypeAny, "passthrough">>>>;
        createdAt: zod.ZodString;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: string;
        eventType: string;
        patientId?: number | null | undefined;
        doctorId?: number | null | undefined;
        candidateId?: number | null | undefined;
        nodeId?: number | null | undefined;
        metadata?: zod.objectOutputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
    }, {
        id: number;
        createdAt: string;
        eventType: string;
        patientId?: number | null | undefined;
        doctorId?: number | null | undefined;
        candidateId?: number | null | undefined;
        nodeId?: number | null | undefined;
        metadata?: zod.objectInputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    totalNodes: number;
    activeNodes: number;
    pendingNodes: number;
    todayCaptures: number;
    byType: {
        label: string;
        count: number;
    }[];
    byDepartment: {
        label: string;
        count: number;
    }[];
    byConfidenceTier: {
        label: string;
        count: number;
    }[];
    recentActivity: {
        id: number;
        createdAt: string;
        eventType: string;
        patientId?: number | null | undefined;
        doctorId?: number | null | undefined;
        candidateId?: number | null | undefined;
        nodeId?: number | null | undefined;
        metadata?: zod.objectOutputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
    }[];
}, {
    totalNodes: number;
    activeNodes: number;
    pendingNodes: number;
    todayCaptures: number;
    byType: {
        label: string;
        count: number;
    }[];
    byDepartment: {
        label: string;
        count: number;
    }[];
    byConfidenceTier: {
        label: string;
        count: number;
    }[];
    recentActivity: {
        id: number;
        createdAt: string;
        eventType: string;
        patientId?: number | null | undefined;
        doctorId?: number | null | undefined;
        candidateId?: number | null | undefined;
        nodeId?: number | null | undefined;
        metadata?: zod.objectInputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
    }[];
}>;
/**
 * @summary List recent event log entries
 */
export declare const ListEventsQueryParams: zod.ZodObject<{
    limit: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
}, "strip", zod.ZodTypeAny, {
    limit?: number | null | undefined;
}, {
    limit?: number | null | undefined;
}>;
export declare const ListEventsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    eventType: zod.ZodString;
    candidateId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    nodeId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    metadata: zod.ZodOptional<zod.ZodNullable<zod.ZodObject<{}, "passthrough", zod.ZodTypeAny, zod.objectOutputType<{}, zod.ZodTypeAny, "passthrough">, zod.objectInputType<{}, zod.ZodTypeAny, "passthrough">>>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: string;
    eventType: string;
    patientId?: number | null | undefined;
    doctorId?: number | null | undefined;
    candidateId?: number | null | undefined;
    nodeId?: number | null | undefined;
    metadata?: zod.objectOutputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
}, {
    id: number;
    createdAt: string;
    eventType: string;
    patientId?: number | null | undefined;
    doctorId?: number | null | undefined;
    candidateId?: number | null | undefined;
    nodeId?: number | null | undefined;
    metadata?: zod.objectInputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
}>;
export declare const ListEventsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    eventType: zod.ZodString;
    candidateId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    nodeId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    doctorId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    patientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    metadata: zod.ZodOptional<zod.ZodNullable<zod.ZodObject<{}, "passthrough", zod.ZodTypeAny, zod.objectOutputType<{}, zod.ZodTypeAny, "passthrough">, zod.objectInputType<{}, zod.ZodTypeAny, "passthrough">>>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: string;
    eventType: string;
    patientId?: number | null | undefined;
    doctorId?: number | null | undefined;
    candidateId?: number | null | undefined;
    nodeId?: number | null | undefined;
    metadata?: zod.objectOutputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
}, {
    id: number;
    createdAt: string;
    eventType: string;
    patientId?: number | null | undefined;
    doctorId?: number | null | undefined;
    candidateId?: number | null | undefined;
    nodeId?: number | null | undefined;
    metadata?: zod.objectInputType<{}, zod.ZodTypeAny, "passthrough"> | null | undefined;
}>, "many">;
//# sourceMappingURL=api.d.ts.map