/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Check if OpenAI API key is configured and usable
 */
export const CheckOpenAIHealthResponse = zod.object({
  "configured": zod.boolean(),
  "status": zod.string()
})


/**
 * @summary List all patients
 */
export const ListPatientsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "mrn": zod.string(),
  "dateOfBirth": zod.string().nullish(),
  "department": zod.string().nullish(),
  "createdAt": zod.string().optional()
})
export const ListPatientsResponse = zod.array(ListPatientsResponseItem)


/**
 * @summary Create a new patient
 */




export const CreatePatientBody = zod.object({
  "name": zod.string().min(1),
  "mrn": zod.string().min(1),
  "dateOfBirth": zod.string().nullish(),
  "department": zod.string().nullish()
})


/**
 * @summary Get patient context nodes
 */
export const GetPatientContextParams = zod.object({
  "patientId": zod.coerce.number()
})

export const GetPatientContextResponse = zod.object({
  "patient": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "mrn": zod.string(),
  "dateOfBirth": zod.string().nullish(),
  "department": zod.string().nullish(),
  "createdAt": zod.string().optional()
}),
  "knowledgeNodes": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.enum(['CONSTRAINT', 'DECISION', 'ANTI_PATTERN', 'FACT']),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.number(),
  "confidence": zod.number(),
  "status": zod.enum(['PENDING_CONFIRMATION', 'ACTIVE', 'DISMISSED', 'MERGED']),
  "level": zod.enum(['patient', 'department', 'organization']),
  "department": zod.string().nullable(),
  "rationale": zod.string().nullish(),
  "patientId": zod.number().nullish(),
  "doctorId": zod.number().nullish(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional()
}))
})


/**
 * @summary List all doctors
 */
export const ListDoctorsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "specialty": zod.string().nullish(),
  "email": zod.string().nullish(),
  "createdAt": zod.string().optional()
})
export const ListDoctorsResponse = zod.array(ListDoctorsResponseItem)


/**
 * @summary Create a new doctor
 */



export const CreateDoctorBody = zod.object({
  "name": zod.string().min(1),
  "specialty": zod.string().nullish(),
  "email": zod.string().nullish()
})


/**
 * @summary Get doctor context — their nodes and stats
 */
export const GetDoctorContextParams = zod.object({
  "doctorId": zod.coerce.number()
})

export const GetDoctorContextResponse = zod.object({
  "doctor": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "specialty": zod.string().nullish(),
  "email": zod.string().nullish(),
  "createdAt": zod.string().optional()
}),
  "knowledgeNodes": zod.array(zod.object({
  "id": zod.number(),
  "type": zod.enum(['CONSTRAINT', 'DECISION', 'ANTI_PATTERN', 'FACT']),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.number(),
  "confidence": zod.number(),
  "status": zod.enum(['PENDING_CONFIRMATION', 'ACTIVE', 'DISMISSED', 'MERGED']),
  "level": zod.enum(['patient', 'department', 'organization']),
  "department": zod.string().nullable(),
  "rationale": zod.string().nullish(),
  "patientId": zod.number().nullish(),
  "doctorId": zod.number().nullish(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional()
}))
})


/**
 * @summary Extract knowledge nodes from transcript using LLM
 */
export const ExtractKnowledgeBody = zod.object({
  "transcript": zod.string(),
  "patientId": zod.number(),
  "doctorId": zod.number()
})

export const ExtractKnowledgeResponseItem = zod.object({
  "id": zod.number(),
  "type": zod.enum(['CONSTRAINT', 'DECISION', 'ANTI_PATTERN', 'FACT']),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.number(),
  "confidence": zod.number(),
  "confidenceTier": zod.enum(['HIGH', 'MEDIUM', 'LOW']),
  "suggestedLevel": zod.enum(['patient', 'department', 'organization']),
  "department": zod.string(),
  "rationale": zod.string(),
  "patientId": zod.number(),
  "doctorId": zod.number(),
  "status": zod.enum(['PENDING', 'CONFIRMED', 'DISMISSED', 'MERGED']).optional(),
  "createdAt": zod.string().optional()
})
export const ExtractKnowledgeResponse = zod.array(ExtractKnowledgeResponseItem)


/**
 * @summary Generate embedding and detect conflicts via cosine similarity search
 */
export const DetectConflictsBody = zod.object({
  "candidateId": zod.number()
})

export const DetectConflictsResponse = zod.object({
  "candidateId": zod.number(),
  "conflictType": zod.enum(['NEW', 'COEXIST', 'UPDATE', 'DUPLICATE']),
  "similarity": zod.number(),
  "existingNode": zod.object({

}).passthrough().nullish()
})


/**
 * @summary Confirm and create a knowledge node
 */
export const ConfirmNodeBody = zod.object({
  "candidateId": zod.number(),
  "editedType": zod.union([zod.literal('CONSTRAINT'),zod.literal('DECISION'),zod.literal('ANTI_PATTERN'),zod.literal('FACT'),zod.literal(null)]).nullish(),
  "editedTitle": zod.string().nullish(),
  "editedContent": zod.string().nullish(),
  "editedRationale": zod.string().nullish()
})


/**
 * @summary Dismiss a capture candidate
 */
export const DismissNodeBody = zod.object({
  "candidateId": zod.number()
})

export const DismissNodeResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})


/**
 * @summary Merge candidate with existing knowledge node
 */
export const MergeNodeBody = zod.object({
  "candidateId": zod.number(),
  "existingNodeId": zod.number(),
  "mergedContent": zod.string().nullish()
})

export const MergeNodeResponse = zod.object({
  "id": zod.number(),
  "type": zod.enum(['CONSTRAINT', 'DECISION', 'ANTI_PATTERN', 'FACT']),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.number(),
  "confidence": zod.number(),
  "status": zod.enum(['PENDING_CONFIRMATION', 'ACTIVE', 'DISMISSED', 'MERGED']),
  "level": zod.enum(['patient', 'department', 'organization']),
  "department": zod.string().nullable(),
  "rationale": zod.string().nullish(),
  "patientId": zod.number().nullish(),
  "doctorId": zod.number().nullish(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Undo an auto-captured node within the 60-second window
 */
export const UndoNodeBody = zod.object({
  "nodeId": zod.number()
})

export const UndoNodeResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})


/**
 * @summary List knowledge nodes with optional filters
 */
export const ListKnowledgeNodesQueryParams = zod.object({
  "patientId": zod.coerce.number().nullish(),
  "doctorId": zod.coerce.number().nullish(),
  "department": zod.coerce.string().nullish(),
  "type": zod.coerce.string().nullish(),
  "status": zod.coerce.string().nullish()
})

export const ListKnowledgeNodesResponseItem = zod.object({
  "id": zod.number(),
  "type": zod.enum(['CONSTRAINT', 'DECISION', 'ANTI_PATTERN', 'FACT']),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.number(),
  "confidence": zod.number(),
  "status": zod.enum(['PENDING_CONFIRMATION', 'ACTIVE', 'DISMISSED', 'MERGED']),
  "level": zod.enum(['patient', 'department', 'organization']),
  "department": zod.string().nullable(),
  "rationale": zod.string().nullish(),
  "patientId": zod.number().nullish(),
  "doctorId": zod.number().nullish(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional()
})
export const ListKnowledgeNodesResponse = zod.array(ListKnowledgeNodesResponseItem)


/**
 * @summary Semantic similarity search over knowledge nodes
 */
export const semanticSearchNodesBodyTopKDefault = 10;

export const SemanticSearchNodesBody = zod.object({
  "query": zod.string(),
  "topK": zod.number().default(semanticSearchNodesBodyTopKDefault)
})

export const SemanticSearchNodesResponseItem = zod.object({
  "node": zod.object({
  "id": zod.number(),
  "type": zod.enum(['CONSTRAINT', 'DECISION', 'ANTI_PATTERN', 'FACT']),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.number(),
  "confidence": zod.number(),
  "status": zod.enum(['PENDING_CONFIRMATION', 'ACTIVE', 'DISMISSED', 'MERGED']),
  "level": zod.enum(['patient', 'department', 'organization']),
  "department": zod.string().nullable(),
  "rationale": zod.string().nullish(),
  "patientId": zod.number().nullish(),
  "doctorId": zod.number().nullish(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional()
}),
  "similarity": zod.number()
})
export const SemanticSearchNodesResponse = zod.array(SemanticSearchNodesResponseItem)


/**
 * @summary Get a single knowledge node
 */
export const GetKnowledgeNodeParams = zod.object({
  "nodeId": zod.coerce.number()
})

export const GetKnowledgeNodeResponse = zod.object({
  "id": zod.number(),
  "type": zod.enum(['CONSTRAINT', 'DECISION', 'ANTI_PATTERN', 'FACT']),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.number(),
  "confidence": zod.number(),
  "status": zod.enum(['PENDING_CONFIRMATION', 'ACTIVE', 'DISMISSED', 'MERGED']),
  "level": zod.enum(['patient', 'department', 'organization']),
  "department": zod.string().nullable(),
  "rationale": zod.string().nullish(),
  "patientId": zod.number().nullish(),
  "doctorId": zod.number().nullish(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Update a knowledge node
 */
export const UpdateKnowledgeNodeParams = zod.object({
  "nodeId": zod.coerce.number()
})

export const UpdateKnowledgeNodeBody = zod.object({
  "type": zod.union([zod.literal('CONSTRAINT'),zod.literal('DECISION'),zod.literal('ANTI_PATTERN'),zod.literal('FACT'),zod.literal(null)]).nullish(),
  "title": zod.string().nullish(),
  "content": zod.string().nullish(),
  "importance": zod.number().nullish(),
  "rationale": zod.string().nullish(),
  "status": zod.union([zod.literal('ACTIVE'),zod.literal('PENDING_CONFIRMATION'),zod.literal('DISMISSED'),zod.literal(null)]).nullish()
})

export const UpdateKnowledgeNodeResponse = zod.object({
  "id": zod.number(),
  "type": zod.enum(['CONSTRAINT', 'DECISION', 'ANTI_PATTERN', 'FACT']),
  "title": zod.string(),
  "content": zod.string(),
  "importance": zod.number(),
  "confidence": zod.number(),
  "status": zod.enum(['PENDING_CONFIRMATION', 'ACTIVE', 'DISMISSED', 'MERGED']),
  "level": zod.enum(['patient', 'department', 'organization']),
  "department": zod.string().nullable(),
  "rationale": zod.string().nullish(),
  "patientId": zod.number().nullish(),
  "doctorId": zod.number().nullish(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional()
})


/**
 * @summary Get dashboard summary of capture pipeline stats
 */
export const GetCaptureSummaryResponse = zod.object({
  "totalNodes": zod.number(),
  "activeNodes": zod.number(),
  "pendingNodes": zod.number(),
  "todayCaptures": zod.number(),
  "byType": zod.array(zod.object({
  "label": zod.string(),
  "count": zod.number()
})),
  "byDepartment": zod.array(zod.object({
  "label": zod.string(),
  "count": zod.number()
})),
  "byConfidenceTier": zod.array(zod.object({
  "label": zod.string(),
  "count": zod.number()
})),
  "recentActivity": zod.array(zod.object({
  "id": zod.number(),
  "eventType": zod.string(),
  "candidateId": zod.number().nullish(),
  "nodeId": zod.number().nullish(),
  "doctorId": zod.number().nullish(),
  "patientId": zod.number().nullish(),
  "metadata": zod.object({

}).passthrough().nullish(),
  "createdAt": zod.string()
}))
})


/**
 * @summary List recent event log entries
 */
export const ListEventsQueryParams = zod.object({
  "limit": zod.coerce.number().nullish()
})

export const ListEventsResponseItem = zod.object({
  "id": zod.number(),
  "eventType": zod.string(),
  "candidateId": zod.number().nullish(),
  "nodeId": zod.number().nullish(),
  "doctorId": zod.number().nullish(),
  "patientId": zod.number().nullish(),
  "metadata": zod.object({

}).passthrough().nullish(),
  "createdAt": zod.string()
})
export const ListEventsResponse = zod.array(ListEventsResponseItem)


