[[pages]]
path = "/"
screenshotTimestamp = "2026-05-30T08:56:33Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/af57e934-45ec-463f-b41c-fd6303ce5457/110a7731-1dfd-4b9e-a333-e235b51a3a22/3HcG0J1"

[[pages]]
path = "/manage"
screenshotTimestamp = "2026-05-30T08:59:33Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/af57e934-45ec-463f-b41c-fd6303ce5457/110a7731-1dfd-4b9e-a333-e235b51a3a22/weBAVp0"

[[pages]]
path = "/pipeline"
screenshotTimestamp = "2026-05-30T08:59:20Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/af57e934-45ec-463f-b41c-fd6303ce5457/110a7731-1dfd-4b9e-a333-e235b51a3a22/SE2H2Rd"

[[pages]]
path = "/knowledge"
screenshotTimestamp = "2026-06-01T04:27:03Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/af57e934-45ec-463f-b41c-fd6303ce5457/110a7731-1dfd-4b9e-a333-e235b51a3a22/bGfKFJ5"
