/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import type { CaptureCandidateConfidenceTier } from './captureCandidateConfidenceTier';
import type { CaptureCandidateStatus } from './captureCandidateStatus';
import type { CaptureCandidateSuggestedLevel } from './captureCandidateSuggestedLevel';
import type { CaptureCandidateType } from './captureCandidateType';
export interface CaptureCandidate {
    id: number;
    type: CaptureCandidateType;
    title: string;
    content: string;
    importance: number;
    confidence: number;
    confidenceTier: CaptureCandidateConfidenceTier;
    suggestedLevel: CaptureCandidateSuggestedLevel;
    department: string;
    rationale: string;
    patientId: number;
    doctorId: number;
    status?: CaptureCandidateStatus;
    createdAt?: string;
}
//# sourceMappingURL=captureCandidate.d.ts.map