/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
export type CaptureCandidateStatus = typeof CaptureCandidateStatus[keyof typeof CaptureCandidateStatus];
export declare const CaptureCandidateStatus: {
    readonly PENDING: "PENDING";
    readonly CONFIRMED: "CONFIRMED";
    readonly DISMISSED: "DISMISSED";
    readonly MERGED: "MERGED";
};
//# sourceMappingURL=captureCandidateStatus.d.ts.map