/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
export type CaptureCandidateConfidenceTier = typeof CaptureCandidateConfidenceTier[keyof typeof CaptureCandidateConfidenceTier];
export declare const CaptureCandidateConfidenceTier: {
    readonly HIGH: "HIGH";
    readonly MEDIUM: "MEDIUM";
    readonly LOW: "LOW";
};
//# sourceMappingURL=captureCandidateConfidenceTier.d.ts.map