/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
export type CaptureCandidateType = typeof CaptureCandidateType[keyof typeof CaptureCandidateType];
export declare const CaptureCandidateType: {
    readonly CONSTRAINT: "CONSTRAINT";
    readonly DECISION: "DECISION";
    readonly ANTI_PATTERN: "ANTI_PATTERN";
    readonly FACT: "FACT";
};
//# sourceMappingURL=captureCandidateType.d.ts.map