/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import type { CountByLabel } from './countByLabel';
import type { EventLog } from './eventLog';
export interface CaptureSummary {
    totalNodes: number;
    activeNodes: number;
    pendingNodes: number;
    todayCaptures: number;
    byType: CountByLabel[];
    byDepartment: CountByLabel[];
    byConfidenceTier: CountByLabel[];
    recentActivity: EventLog[];
}
//# sourceMappingURL=captureSummary.d.ts.map