/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
export type CaptureCandidateSuggestedLevel = typeof CaptureCandidateSuggestedLevel[keyof typeof CaptureCandidateSuggestedLevel];
export declare const CaptureCandidateSuggestedLevel: {
    readonly patient: "patient";
    readonly department: "department";
    readonly organization: "organization";
};
//# sourceMappingURL=captureCandidateSuggestedLevel.d.ts.map