/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import type { ConflictResultConflictType } from './conflictResultConflictType';
import type { ConflictResultExistingNode } from './conflictResultExistingNode';

export interface ConflictResult {
  candidateId: number;
  conflictType: ConflictResultConflictType;
  similarity: number;
  /** @nullable */
  existingNode?: ConflictResultExistingNode;
}
