/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */

export type ConflictResultConflictType = typeof ConflictResultConflictType[keyof typeof ConflictResultConflictType];


export const ConflictResultConflictType = {
  NEW: 'NEW',
  COEXIST: 'COEXIST',
  UPDATE: 'UPDATE',
  DUPLICATE: 'DUPLICATE',
} as const;
