/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import type { Doctor } from './doctor';
import type { KnowledgeNode } from './knowledgeNode';

export interface DoctorContext {
  doctor: Doctor;
  knowledgeNodes: KnowledgeNode[];
}
