/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */

export interface DoctorInput {
  /** @minLength 1 */
  name: string;
  /** @nullable */
  specialty?: string | null;
  /** @nullable */
  email?: string | null;
}
