/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import type { EventLogMetadata } from './eventLogMetadata';

export interface EventLog {
  id: number;
  eventType: string;
  /** @nullable */
  candidateId?: number | null;
  /** @nullable */
  nodeId?: number | null;
  /** @nullable */
  doctorId?: number | null;
  /** @nullable */
  patientId?: number | null;
  /** @nullable */
  metadata?: EventLogMetadata;
  createdAt: string;
}
