/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import type { KnowledgeNodeUpdateStatus } from './knowledgeNodeUpdateStatus';
import type { KnowledgeNodeUpdateType } from './knowledgeNodeUpdateType';

export interface KnowledgeNodeUpdate {
  /** @nullable */
  type?: KnowledgeNodeUpdateType;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  importance?: number | null;
  /** @nullable */
  rationale?: string | null;
  /** @nullable */
  status?: KnowledgeNodeUpdateStatus;
}
