/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import type { KnowledgeNodeLevel } from './knowledgeNodeLevel';
import type { KnowledgeNodeStatus } from './knowledgeNodeStatus';
import type { KnowledgeNodeType } from './knowledgeNodeType';

export interface KnowledgeNode {
  id: number;
  type: KnowledgeNodeType;
  title: string;
  content: string;
  importance: number;
  confidence: number;
  status: KnowledgeNodeStatus;
  level: KnowledgeNodeLevel;
  /** @nullable */
  department: string | null;
  /** @nullable */
  rationale?: string | null;
  /** @nullable */
  patientId?: number | null;
  /** @nullable */
  doctorId?: number | null;
  createdAt?: string;
  updatedAt?: string;
}
