/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */

export type KnowledgeNodeStatus = typeof KnowledgeNodeStatus[keyof typeof KnowledgeNodeStatus];


export const KnowledgeNodeStatus = {
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  ACTIVE: 'ACTIVE',
  DISMISSED: 'DISMISSED',
  MERGED: 'MERGED',
} as const;
