/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type KnowledgeNodeUpdateStatus = typeof KnowledgeNodeUpdateStatus[keyof typeof KnowledgeNodeUpdateStatus] | null;


export const KnowledgeNodeUpdateStatus = {
  ACTIVE: 'ACTIVE',
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  DISMISSED: 'DISMISSED',
} as const;
