/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */

export type KnowledgeNodeType = typeof KnowledgeNodeType[keyof typeof KnowledgeNodeType];


export const KnowledgeNodeType = {
  CONSTRAINT: 'CONSTRAINT',
  DECISION: 'DECISION',
  ANTI_PATTERN: 'ANTI_PATTERN',
  FACT: 'FACT',
} as const;
