/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */

export type KnowledgeNodeLevel = typeof KnowledgeNodeLevel[keyof typeof KnowledgeNodeLevel];


export const KnowledgeNodeLevel = {
  patient: 'patient',
  department: 'department',
  organization: 'organization',
} as const;
