/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */

export type ListKnowledgeNodesParams = {
/**
 * @nullable
 */
patientId?: number | null;
/**
 * @nullable
 */
doctorId?: number | null;
/**
 * @nullable
 */
department?: string | null;
/**
 * @nullable
 */
type?: string | null;
/**
 * @nullable
 */
status?: string | null;
};
