/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */

export interface Patient {
  id: number;
  name: string;
  mrn: string;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  department?: string | null;
  createdAt?: string;
}
