/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Knowledge Capture Pipeline API
 * OpenAPI spec version: 0.1.0
 */
import type { KnowledgeNode } from './knowledgeNode';
import type { Patient } from './patient';

export interface PatientContext {
  patient: Patient;
  knowledgeNodes: KnowledgeNode[];
}
